language: python
python:
  - "3.6"
  - "3.7"
jobs:
  include:
    - name: "Linux build"
      os: linux
    - name: "MacOS build"
      os: osx
      osx_image: xcode9.4
script:
  - python -m unittest discover