language: python
jobs:
  include:
    - name: "Python 3.7 Linux build"
      os: linux
      language: python
      python: "3.7"
    - name: "Python 3.7.4 MacOS build"
      os: osx
      osx_image: xcode11.2
      language: shell
script:
  - python3 -m unittest discover -p "*_test.py"