language: python
jobs:
  include:
    - name: "Python 3.7 Linux build"
      os: linux
      language: python
      python: "3.7"
    - name: "Python 3.7.4 MacOS build"
      os: osx
      osx_image: xcode11.2
      language: shell
    - name: "Python 3.7.4 Windows build"
      os: windows
      language: shell
      before_install:
        - choco install python --version 3.7.4
        - python -m pip install --upgrade pip
      env: PATH=/c/Python37:/c/Python37/Scripts:$PATH
script:
  - python3 -m unittest discover -p "*_test.py"